sudo: required

services:
  - docker

language: go

go:
  - 1.7

go_import_path: github.com/supergiant/supergiant-alpha-signup


install:
  - go get github.com/karalabe/xgo
  - go get -u github.com/jteeuwen/go-bindata/...
  - npm install -g npm@5.3.0
  - npm install -g @angular/cli@1.4.1

script:
  - travis_wait 60 build/travis_build.sh
